default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blogapp_development
  username: postgres
  password: sadaf313

test:
  <<: *default
  database: blogapp_test
  username: postgres
  password: sadaf313

production:
  <<: *default
  database: blogapp_production
  username: blogapp
  password: <%= ENV['BLOGAPP_DATABASE_PASSWORD'] %>
